openapi: "3.0.1"
info:
  title: "Mi API"
  version: "1.0"
paths:
  /v1/product/get/movies:
    get:
      summary: "Invoca la Lambda"
      responses:
        "200":
          description: "Éxito"
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:mi-lambda/invocations
        httpMethod: "POST"
        type: "AWS_PROXY"
